//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "plotsystem_builders")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub name: String,
    pub score: i32,
    pub completed_plots: i32,
    pub first_slot: Option<i32>,
    pub second_slot: Option<i32>,
    pub third_slot: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::plotsystem_plots::Entity")]
    PlotsystemPlots,
    #[sea_orm(has_many = "super::plotsystem_reviews::Entity")]
    PlotsystemReviews,
}

impl Related<super::plotsystem_plots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlotsystemPlots.def()
    }
}

impl Related<super::plotsystem_reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlotsystemReviews.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
