//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "plotsystem_builder_is_reviewer")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub builder_uuid: String,
    pub buildteam_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::plotsystem_builders::Entity",
        from = "Column::BuilderUuid",
        to = "super::plotsystem_builders::Column::Uuid",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    PlotsystemBuilders,
    #[sea_orm(
        belongs_to = "super::plotsystem_buildteams::Entity",
        from = "Column::BuildteamId",
        to = "super::plotsystem_buildteams::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    PlotsystemBuildteams,
}

impl Related<super::plotsystem_builders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlotsystemBuilders.def()
    }
}

impl Related<super::plotsystem_buildteams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlotsystemBuildteams.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
