//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "plotsystem_buildteams")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub api_key_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::plotsystem_api_keys::Entity",
        from = "Column::ApiKeyId",
        to = "super::plotsystem_api_keys::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    PlotsystemApiKeys,
    #[sea_orm(has_many = "super::plotsystem_builder_is_reviewer::Entity")]
    PlotsystemBuilderIsReviewer,
    #[sea_orm(has_many = "super::plotsystem_buildteam_has_countries::Entity")]
    PlotsystemBuildteamHasCountries,
}

impl Related<super::plotsystem_api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlotsystemApiKeys.def()
    }
}

impl Related<super::plotsystem_builder_is_reviewer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlotsystemBuilderIsReviewer.def()
    }
}

impl Related<super::plotsystem_buildteam_has_countries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlotsystemBuildteamHasCountries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
