//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "api_keys")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub api_key: String,
    #[sea_orm(unique)]
    pub name: String,
    pub country_id: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::plotsystem_countries::Entity",
        from = "Column::CountryId",
        to = "super::plotsystem_countries::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    PlotsystemCountries,
}

impl Related<super::plotsystem_countries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlotsystemCountries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
